#### somni.dotfiles.linux ####
##  KMSCON  Configurations  ##

### Graphics options
drm
gpus=all
hwaccel
use-original-mode

### Fonts
font-engine=pango
font-size=14
font-name=D2CodingLigature Nerd Font Mono, Symbols Nerd Font, D2Coding

### Input options
# Keyboard Shortcuts
grab-scroll-up=<Logo>Up
grab-scroll-down=<Logo>Down
grab-page-up=Prior
grab-page-down=Next
grab-zoom-in=<Ctrl>Plus
grab-zoom-out=<Ctrl>Minus
grab-rotate-cw=<Logo>Plus
grab-rotate-ccw=<Logo>Minus

# Enable mouse
mouse

### Theme options
palette=solarized-black
