# vim:fileencoding=utf-8:foldmethod=marker

#### somni.dotfiles.linux ####
##   Kitty Configurations   ##

### ** Shell integration reset **
shell_integration no-cursor

### ** Fonts **
font_family      family="D2Coding"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

### ** Nerd Fonts Symbols **
###   - Codepoints can be found at https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points
###   - Make sure to install 'D2CodingLigature Nerd Font Mono' font.
###     - For Arch Linux the package is `ttf-d2coding-nerd`
###     - For macOS Homebrew the package is `font-d2coding-nerd-font`
# SetiUI + Custom
symbol_map U+E5FA-U+E6B7                                    D2CodingLigature Nerd Font Mono
# Devicons
symbol_map U+E700-U+E8EF                                    D2CodingLigature Nerd Font Mono
# Font Awesome
symbol_map U+ED00-U+F2FF                                    D2CodingLigature Nerd Font Mono
# Font Awesome Extension
symbol_map U+E200-U+E2A9                                    D2CodingLigature Nerd Font Mono
# Material Design Icons
symbol_map U+F0001-U+F1AF0                                  D2CodingLigature Nerd Font Mono
# Weather
symbol_map U+E300-U+E3E3                                    D2CodingLigature Nerd Font Mono
# Font Logos
symbol_map U+F300-U+F381                                    D2CodingLigature Nerd Font Mono
# Pomicons
symbol_map U+E000-U+E00A                                    D2CodingLigature Nerd Font Mono
# Codicons
symbol_map U+EA60-U+EC1E                                    D2CodingLigature Nerd Font Mono
# Heavy Angle Brackets
symbol_map U+276C-U+2771                                    D2CodingLigature Nerd Font Mono
# Box Drawing
symbol_map U+2500-U+259F                                    D2CodingLigature Nerd Font Mono
# Progress
symbol_map U+EE00-U+EE0B                                    D2CodingLigature Nerd Font Mono
# IEC Power Symbols
symbol_map U+23FB-U+23FE,U+2B58                             D2CodingLigature Nerd Font Mono
# Octicons
symbol_map U+F400-U+F533,U+2265,U+26A1                      D2CodingLigature Nerd Font Mono
# Powerline Symbols
symbol_map U+E0A0-U+E0A2,U+E0B0-U+E0B3                      D2CodingLigature Nerd Font Mono
# Powerline Extra Symbols
symbol_map U+E0A3,U+E0B4-U+E0C8,U+E0CA,U+E0CC-U+E0D7,U+2630 D2CodingLigature Nerd Font Mono

### ** Cursor **
cursor_shape block
cursor_shape_unfocused unchanged
cursor_blink_interval 0.5 ease-in ease-out
cursor_stop_blinking_after 0
cursor_trail 200

### ** Scrollback / Scrollbar **
scrollback_lines 5000
scrollbar always
scrollbar_width 0.5
scrollbar_hover_width 0.75
scrollbar_radius 0.5
scrollbar_gap 1
scrollbar_min_handle_height 2
scrollbar_handle_opacity 0.33
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0.025

### ** Theme include **
include themes/Pnevma.conf

### ** Visual Bell **
visual_bell_duration 0.5 step-start ease-out
window_alert_on_bell yes

### ** Window **
window_padding_width 0 4
remember_window_size no
initial_window_width 120c
initial_window_height 36c

### ** Background **
background_opacity 0.6
background_blur 8

### ** Linux **
wayland_enable_ime yes

### ** macOS **
macos_quit_when_last_window_closed yes
