# vim:fileencoding=utf-8:foldmethod=marker

### Shell integration reset
shell_integration no-cursor

### Fonts
font_family      family="D2Coding"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

### Nerd Fonts Symbols
###   - Codepoints can be found at https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points
# SetiUI + Custom
symbol_map U+E5FA-U+E6B7   Symbols Nerd Font Mono
# Devicons
symbol_map U+E700-U+E8EF   Symbols Nerd Font Mono
# Font Awesome
symbol_map U+ED00-U+F2FF   Symbols Nerd Font Mono
# Font Awesome Extension
symbol_map U+E200-U+E2A9   Symbols Nerd Font Mono
# Material Design Icons
symbol_map U+F0001-U+F1AF0 Symbols Nerd Font Mono
# Weather
symbol_map U+E300-U+E3E3   Symbols Nerd Font Mono
# Font Logos
symbol_map U+F300-U+F381   Symbols Nerd Font Mono
# Pomicons
symbol_map U+E000-U+E00A   Symbols Nerd Font Mono
# Codicons
symbol_map U+EA60-U+EC1E   Symbols Nerd Font Mono
# Heavy Angle Brackets
symbol_map U+276C-U+2771   Symbols Nerd Font Mono
# Box Drawing
symbol_map U+2500-U+259F   Symbols Nerd Font Mono
# Progress
symbol_map U+EE00-U+EE0B   Symbols Nerd Font Mono
# IEC Power Symbols
symbol_map U+23FB-U+23FE,U+2B58        Symbols Nerd Font Mono
# Octicons
symbol_map U+F400-U+F533,U+2265,U+26A1 Symbols Nerd Font Mono
# Powerline Symbols
symbol_map U+E0A0-U+E0A2,U+E0B0-U+E0B3 Symbols Nerd Font Mono
# Powerline Extra Symbols
symbol_map U+E0A3,U+E0B4-U+E0C8,U+E0CA,U+E0CC-U+E0D7,U+2630 Symbols Nerd Font Mono

### Cursor
cursor_shape block
cursor_shape_unfocused unchanged
cursor_blink_interval 0.5 ease-in ease-out
cursor_stop_blinking_after 0
cursor_trail 200

### Scrollback / Scrollbar
scrollback_lines 5000
scrollbar always
scrollbar_width 0.5
scrollbar_hover_width 0.75
scrollbar_radius 0.5
scrollbar_gap 1
scrollbar_min_handle_height 2
scrollbar_handle_opacity 0.33
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0.025

### Theme include
include themes/Pnevma.conf

### Visual Bell
visual_bell_duration 0.5 step-start ease-out
window_alert_on_bell yes

### Window
window_padding_width 0 4

### Background
background_opacity 0.5
background_blur 4

### Linux
wayland_enable_ime yes

### macOS
macos_quit_when_last_window_closed yes
