# 키보드 자판
Keyboard=Dubeolsik
# 자동 재배열
AutoReorder=False
# Combine on Double Stroke
CombiOnDoubleStroke=False
# Combine Non Choseong
NonChoseongCombi=True
# 단어 단위 입력
WordCommit=False
# 한자 모드
HanjaMode=False

[HanjaModeToggleKey]
0=Hangul_Hanja

[PrevPage]
0=Up

[NextPage]
0=Down

[PrevCandidate]
0=Left

[NextCandidate]
0=Right

