# 초기 모드
InitialMode=Hiragana
# Shared Input State
InputState="Follow Global Configuration"
# 세로 후보 목록
Vertical=True
# 어법 확장 (세로 후보 목록 필요)
ExpandMode="On Focus"
# 사전편집 시작 부분에 포함된 사전편집 커서 수정
PreeditCursorPositionAtBeginning=False
# 사용을 확장할 단축키
ExpandKey=Control+Alt+H

