[config]

[templates]

[templates.niri-somni]
input_path = "~/.config/noctalia/templates/niri-somni.kdl"
output_path = "~/.config/niri/noctalia-somni.kdl"

[templates.sysc-greet]
input_path = "~/.config/noctalia/templates/sysc-greet.toml"
output_path = "~/.config/sysc-greet/themes/noctalia.toml"
