[Metadata]
Name=somni-Noctalia
Version=0.0
Author=somni
Description="Fcitx5 theme by somni with Noctalia Shell color scheme synchronization"
ScaleWithDPI=True

[InputPanel]
Font=Sans 12
NormalColor={{ colors.on_surface.default.hex }}
HighlightCandidateColor={{ colors.primary.default.hex }}
CommentTextSizeFactor=75
HighlightCandidateCommentColor={{ colors.secondary.default.hex }}
#HighlightColor={{ colors.primary.default.hex }}
#HighlightBackgroundColor={{ colors.surface_variant.default.hex }}
Spacing=0
EnableBlur=True

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/Background]
Color={{ colors.surface.default.hex }}dd
BorderColor={{ colors.primary.default.hex }}
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color={{ colors.surface_variant.default.hex }}dd

[InputPanel/Highlight/Margin]
Left=4
Right=4
Top=4
Bottom=4

[Menu]
NormalColor={{ colors.on_surface.default.hex }}
HighlightCandidateColor={{ colors.primary.default.hex }}

[Menu/Background]
Color={{ colors.surface.default.hex }}dd
BorderColor={{ colors.primary.default.hex }}
BorderWidth=1

[Menu/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/Highlight]
Color={{ colors.surface_variant.default.hex }}dd

[Menu/Highlight/Margin]
Left=4
Right=4
Top=4
Bottom=4